sudo: false

language: node_js
node_js:
  - 9

install:
  - npm install

script:
  - npm test

branches:
  only:
    - master

deploy:
  provider: heroku
  skip_cleanup: true
script: .travis/pu.sh
 on:
   branch: master
   tags: false
app: "pure-wildwood-16458"
api_key:
secure: "20a351e7-b49a-405e-9ec0-e5258c4cb10c"
  