sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "pure-wildwood-16458"
  api_key:
    secure: "20a351e7-b49a-405e-9ec0-e5258c4cb10c"
  skip_cleanup: true